"""add auth fields to users

Revision ID: 7b1b1e340403
Revises: 453796da9d3c
Create Date: 2025-08-21 19:02:44.021144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b1b1e340403'
down_revision: Union[str, Sequence[str], None] = '453796da9d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='pending_users')
    op.drop_table('pending_users')
    op.alter_column('agencies', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_agencies_city_id'), 'agencies', ['city_id'], unique=False)
    op.create_index(op.f('ix_agencies_user_id'), 'agencies', ['user_id'], unique=False)
    op.drop_constraint(op.f('agencies_ibfk_1'), 'agencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_city'), 'agencies', type_='foreignkey')
    op.create_foreign_key(None, 'agencies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agencies', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inquiries', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_inquiries_registration_id'), 'inquiries', ['registration_id'], unique=False)
    op.drop_constraint(op.f('inquiries_ibfk_1'), 'inquiries', type_='foreignkey')
    op.create_foreign_key(None, 'inquiries', 'agencies', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.alter_column('packages', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_packages_registration_id'), 'packages', ['registration_id'], unique=False)
    op.drop_constraint(op.f('packages_ibfk_1'), 'packages', type_='foreignkey')
    op.create_foreign_key(None, 'packages', 'agencies', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.create_foreign_key(op.f('packages_ibfk_1'), 'packages', 'agencies', ['registration_id'], ['registration_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_packages_registration_id'), table_name='packages')
    op.alter_column('packages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.create_foreign_key(op.f('inquiries_ibfk_1'), 'inquiries', 'agencies', ['registration_id'], ['registration_id'])
    op.drop_index(op.f('ix_inquiries_registration_id'), table_name='inquiries')
    op.alter_column('inquiries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'agencies', type_='foreignkey')
    op.drop_constraint(None, 'agencies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_city'), 'agencies', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(op.f('agencies_ibfk_1'), 'agencies', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_agencies_user_id'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_city_id'), table_name='agencies')
    op.alter_column('agencies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.create_table('pending_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('otp_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('otp_sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'pending_users', ['email'], unique=True)
    # ### end Alembic commands ###
