"""add AgencyDetail 1:1

Revision ID: a59c79fff0bd
Revises: 2a2c744ced2b
Create Date: 2025-09-11 20:58:22.574715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a59c79fff0bd'
down_revision: Union[str, Sequence[str], None] = '2a2c744ced2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agencies', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=True)
    op.drop_index(op.f('ix_agencies_city_id'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_user_id'), table_name='agencies')
    op.drop_constraint(op.f('agencies_ibfk_2'), 'agencies', type_='foreignkey')
    op.drop_constraint(op.f('agencies_ibfk_1'), 'agencies', type_='foreignkey')
    op.create_foreign_key(None, 'agencies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'agencies', 'cities', ['city_id'], ['id'])
    op.alter_column('agency_details', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agency_details', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('inquiries', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=True)
    op.drop_index(op.f('ix_inquiries_registration_id'), table_name='inquiries')
    op.drop_constraint(op.f('inquiries_ibfk_1'), 'inquiries', type_='foreignkey')
    op.create_foreign_key(None, 'inquiries', 'agencies', ['registration_id'], ['registration_id'])
    op.alter_column('packages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=True)
    op.drop_index(op.f('ix_packages_registration_id'), table_name='packages')
    op.drop_constraint(op.f('packages_ibfk_1'), 'packages', type_='foreignkey')
    op.create_foreign_key(None, 'packages', 'agencies', ['registration_id'], ['registration_id'])
    op.alter_column('users', 'last_login_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.create_foreign_key(op.f('packages_ibfk_1'), 'packages', 'agencies', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_packages_registration_id'), 'packages', ['registration_id'], unique=False)
    op.alter_column('packages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.create_foreign_key(op.f('inquiries_ibfk_1'), 'inquiries', 'agencies', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_inquiries_registration_id'), 'inquiries', ['registration_id'], unique=False)
    op.alter_column('inquiries', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    op.alter_column('agency_details', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('agency_details', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.drop_constraint(None, 'agencies', type_='foreignkey')
    op.drop_constraint(None, 'agencies', type_='foreignkey')
    op.create_foreign_key(op.f('agencies_ibfk_1'), 'agencies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agencies_ibfk_2'), 'agencies', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_agencies_user_id'), 'agencies', ['user_id'], unique=False)
    op.create_index(op.f('ix_agencies_city_id'), 'agencies', ['city_id'], unique=False)
    op.alter_column('agencies', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    # ### end Alembic commands ###
