"""add price_single to package_prices

Revision ID: e6a66df92843
Revises: 5802609933b5
Create Date: 2025-11-29 21:53:26.144154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6a66df92843'
down_revision: Union[str, Sequence[str], None] = '5802609933b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_prices', sa.Column('price_single', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('package_prices', sa.Column('price_double', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('package_prices', sa.Column('price_triple', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('package_prices', sa.Column('price_quad', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('package_prices', sa.Column('note', sa.String(length=255), nullable=True))
    op.add_column('package_prices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('package_prices', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'package_prices', ['package_id'])
    op.drop_column('package_prices', 'price_per_person')
    op.drop_column('package_prices', 'room_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_prices', sa.Column('room_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False))
    op.add_column('package_prices', sa.Column('price_per_person', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'package_prices', type_='unique')
    op.alter_column('package_prices', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('package_prices', 'updated_at')
    op.drop_column('package_prices', 'note')
    op.drop_column('package_prices', 'price_quad')
    op.drop_column('package_prices', 'price_triple')
    op.drop_column('package_prices', 'price_double')
    op.drop_column('package_prices', 'price_single')
    # ### end Alembic commands ###
